### ISSUE TITLE
Remember to link iOS bundle

### ISSUE THREAD

**Issue by alizahid** [React-Native-Nation/react-native-satismeter#1]
Hey,

I'm trying to add this package to my app, but running into an issue.

I see in Xcode logs that it says `SatisMeter Service is already running` but when I try `RNSatismeter.run(true)`, nothing pops up.

I think I missed the _Remember to link iOS bundle_ part, but not sure what that means? Tried Google, but didn't help.

Can you please point me in the right direction? Thank you!

**Comment by jamesjara** [comment]
fixed in https://github.com/React-Native-Nation/react-native-satismeter/commit/8cfb759dae4dbdfdf66d2a06325ce48df2e309cb
